/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.usuario.preguntas;

import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.Popup;
import quemquersermillonario.dao.interfaces.PreguntaDAO;
import quemquersermillonario.dao.interfaces.implementation.PreguntaDAOImpl;
import quemquersermillonario.dao.logica.ComprobacionText;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.VentanasLogica;
import quemquersermillonario.dto.Categoria;
import quemquersermillonario.dto.Dificultad;
import quemquersermillonario.dto.Pregunta;
import quemquersermillonario.dto.Respuesta;
import quemquersermillonario.dto.complejas.OpcionesFijas;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelCategoria;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelDificultad;

/**
 *
 * @author alvaro
 */
public class PantallaUsuarioPreguntaDatos extends javax.swing.JDialog {

    private boolean esModificacion;
    private Pregunta pregunta;
    private PreguntaDAO preguntaDAO;
    private Popup popup;

    /**
     * Creates new form PantallaUsuarioPreguntaDatos
     *
     * @param parent
     * @param modal
     * @param esModificacion
     * @param pregunta
     */
    public PantallaUsuarioPreguntaDatos(java.awt.Frame parent, boolean modal, boolean esModificacion, Pregunta pregunta) {
        super(parent, modal);
        initComponents();
        this.esModificacion = esModificacion;
        this.preguntaDAO = new PreguntaDAOImpl();
        this.jComboBoxCategoria.setModel(ComboBoxModelCategoria.getCategoriaComboBoxModel());
        this.jComboBoxDificultad.setModel(ComboBoxModelDificultad.getDificultadComboBoxModel());
        if (esModificacion == false) {
            this.pregunta = preguntaDAO.inicializarPregunta();
            this.setTitle(Lenguaje.getString("NuevaPregunta"));

        } else {
            this.pregunta = pregunta;
            this.ObjetoACampos();
            this.setTitle(Lenguaje.getString("ActualizarPregunta"));
        }
        this.jLabelCategoria.setText(Lenguaje.getString("Categoria"));
        this.jLabelDificultad.setText(Lenguaje.getString("Dificultad"));
        this.jLabelPregunta.setText(Lenguaje.getString("Pregunta"));
        this.jLabelRespuestaCorrecta.setText(Lenguaje.getString("RespuestaCorrecta"));
        this.jLabelRespuestaIncorrecta1.setText(Lenguaje.getString("RespuestaIncorrecta"));
        this.jLabelRespuestaIncorrecta2.setText(Lenguaje.getString("RespuestaIncorrecta"));
        this.jLabelRespuestaIncorrecta3.setText(Lenguaje.getString("RespuestaIncorrecta"));
        VentanasLogica.estilizarVentaja(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPregunta = new javax.swing.JLabel();
        jTextFieldPregunta1 = new javax.swing.JTextField();
        jLabelRespuestaCorrecta = new javax.swing.JLabel();
        jTextFieldRespuesta1 = new javax.swing.JTextField();
        jLabelRespuestaIncorrecta1 = new javax.swing.JLabel();
        jTextFieldRespuesta2 = new javax.swing.JTextField();
        jLabelRespuestaIncorrecta2 = new javax.swing.JLabel();
        jTextFieldRespuesta3 = new javax.swing.JTextField();
        jLabelRespuestaIncorrecta3 = new javax.swing.JLabel();
        jTextFieldRespuesta4 = new javax.swing.JTextField();
        jLabelDificultad = new javax.swing.JLabel();
        jComboBoxDificultad = new javax.swing.JComboBox<>();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelInformacion = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 10, 20));

        jLabelPregunta.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelPregunta.setText("Pregunta:");
        jPanel1.add(jLabelPregunta);

        jTextFieldPregunta1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldPregunta1.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldPregunta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldPregunta1);
        jTextFieldPregunta1.getAccessibleContext().setAccessibleName("Pregunta");

        jLabelRespuestaCorrecta.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaCorrecta.setText("Respuesta Correcta:");
        jPanel1.add(jLabelRespuestaCorrecta);

        jTextFieldRespuesta1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldRespuesta1.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldRespuesta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldRespuesta1);

        jLabelRespuestaIncorrecta1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaIncorrecta1.setText("Respuesta Incorrecta:");
        jPanel1.add(jLabelRespuestaIncorrecta1);

        jTextFieldRespuesta2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldRespuesta2.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldRespuesta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldRespuesta2);

        jLabelRespuestaIncorrecta2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaIncorrecta2.setText("Respuesta Incorrecta:");
        jPanel1.add(jLabelRespuestaIncorrecta2);

        jTextFieldRespuesta3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldRespuesta3.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldRespuesta3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldRespuesta3);

        jLabelRespuestaIncorrecta3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaIncorrecta3.setText("Respuesta Incorrecta:");
        jPanel1.add(jLabelRespuestaIncorrecta3);

        jTextFieldRespuesta4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldRespuesta4.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldRespuesta4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldRespuesta4);

        jLabelDificultad.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelDificultad.setText("Dificultad:");
        jPanel1.add(jLabelDificultad);

        jComboBoxDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxDificultad);

        jLabelCategoria.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelCategoria.setText("Categoria:");
        jPanel1.add(jLabelCategoria);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxCategoria);

        jLabelInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/informacion.png"))); // NOI18N
        jLabelInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });

        jButtonAceptar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/aceptar_normal.png"))); // NOI18N
        jButtonAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/aceptar_clicado.png"))); // NOI18N
        jButtonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_normal.png"))); // NOI18N
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_clicado.png"))); // NOI18N
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)))
                .addGap(10, 10, 10)
                .addComponent(jLabelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabelInformacion.getAccessibleContext().setAccessibleName("Informacion.Preguntas");
        jButtonAceptar.getAccessibleContext().setAccessibleName("Aceptar");
        jButtonSalir.getAccessibleContext().setAccessibleName("Salir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if (ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta1) && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta1)
                && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta2) && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta3)
                && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta4)) {
            if (!esModificacion) {
                camposAObjeto();
                preguntaDAO.guardar(pregunta);
                JOptionPane.showMessageDialog(this, Lenguaje.getString("Pregunta.Registrada"), Lenguaje.getString("Correcto"), JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } else {
                camposAObjeto();
                preguntaDAO.actualizar(pregunta);
                JOptionPane.showMessageDialog(this, Lenguaje.getString("Pregunta.Actualizada"), Lenguaje.getString("Correcto"), JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, Lenguaje.getString("RellenarCampos"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void tamanoMaximo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamanoMaximo
        // TODO add your handling code here:

        JTextField jtf = (JTextField) evt.getComponent();
        int tam = 40;
        if ((jtf.getAccessibleContext().getAccessibleName() != null) && (jtf.getAccessibleContext().getAccessibleName().equals("Pregunta"))) {
            tam = 80;
        }
        if (!ComprobacionText.comprobacionTamanoJTextField(jtf, tam)) {
            JOptionPane.showMessageDialog(this, Lenguaje.getString("Error.Texto.Longitud"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_tamanoMaximo

    private void ratonEntra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonEntra
        // TODO add your handling code here:
        String nombre = "";
        try {
            JLabel jl = (JLabel) evt.getSource();
            nombre = jl.getAccessibleContext().getAccessibleName();
        } catch (Exception e) {
            try {
                JButton jb = (JButton) evt.getSource();
                nombre = jb.getAccessibleContext().getAccessibleName();
            } catch (Exception a) {
                nombre = "Error";
            }
        }

        popup = VentanasLogica.mensajePopup(popup, nombre, evt);
        popup.show();
    }//GEN-LAST:event_ratonEntra

    private void ratonSale(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonSale
        // TODO add your handling code here:
        popup.hide();
    }//GEN-LAST:event_ratonSale

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, Lenguaje.getString("Confirmacion.Salir"), Lenguaje.getString("Salir"), JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void camposAObjeto() {
        this.pregunta.setActivo(1);
        this.pregunta.setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.setCategoria((Categoria) jComboBoxCategoria.getSelectedItem());
        this.pregunta.setDificultad((Dificultad) jComboBoxDificultad.getSelectedItem());
        this.pregunta.setUsuario(OpcionesFijas.getUsuario());
        this.pregunta.setNombre(jTextFieldPregunta1.getText());

        //Respuestas
        //Respuesta 1 Correcta
        this.pregunta.getListaRespuestas().get(0).setActivo(1);
        this.pregunta.getListaRespuestas().get(0).setCorrecta(1);
        this.pregunta.getListaRespuestas().get(0).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(0).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(0).setNombre(jTextFieldRespuesta1.getText());
        //Respuesta 2
        this.pregunta.getListaRespuestas().get(1).setActivo(1);
        this.pregunta.getListaRespuestas().get(1).setCorrecta(0);
        this.pregunta.getListaRespuestas().get(1).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(1).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(1).setNombre(jTextFieldRespuesta2.getText());
        //Respuesta 3
        this.pregunta.getListaRespuestas().get(2).setActivo(1);
        this.pregunta.getListaRespuestas().get(2).setCorrecta(0);
        this.pregunta.getListaRespuestas().get(2).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(2).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(2).setNombre(jTextFieldRespuesta3.getText());
        //Respuesta 4
        this.pregunta.getListaRespuestas().get(3).setActivo(1);
        this.pregunta.getListaRespuestas().get(3).setCorrecta(0);
        this.pregunta.getListaRespuestas().get(3).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(3).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(3).setNombre(jTextFieldRespuesta4.getText());

        if (!esModificacion) {
            this.pregunta.setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(0).setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(1).setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(2).setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(3).setFechaCreacion(OpcionesFijas.fechaActual());
        }
    }

    private void ObjetoACampos() {
        this.jTextFieldPregunta1.setText(this.pregunta.getNombre());
        int i = 0;
        for (Respuesta res : this.pregunta.getListaRespuestas()) {
            if (res.getCorrecta() == 1) {
                this.jTextFieldRespuesta1.setText(res.getNombre());
            } else {
                switch (i) {
                    case 0:
                        jTextFieldRespuesta2.setText(res.getNombre());
                        break;
                    case 1:
                        jTextFieldRespuesta3.setText(res.getNombre());
                        break;
                    case 2:
                        jTextFieldRespuesta4.setText(res.getNombre());
                        break;
                }
                i++;
            }
        }

        this.jComboBoxCategoria.setSelectedIndex(ComboBoxModelCategoria.getIndexOfCategoria(this.pregunta.getCategoria()));
        this.jComboBoxDificultad.setSelectedIndex(ComboBoxModelDificultad.getIndexOfDificultad(this.pregunta.getDificultad()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxDificultad;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDificultad;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelRespuestaCorrecta;
    private javax.swing.JLabel jLabelRespuestaIncorrecta1;
    private javax.swing.JLabel jLabelRespuestaIncorrecta2;
    private javax.swing.JLabel jLabelRespuestaIncorrecta3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPregunta1;
    private javax.swing.JTextField jTextFieldRespuesta1;
    private javax.swing.JTextField jTextFieldRespuesta2;
    private javax.swing.JTextField jTextFieldRespuesta3;
    private javax.swing.JTextField jTextFieldRespuesta4;
    // End of variables declaration//GEN-END:variables
}
