/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.usuario.preguntas;

import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import quemquersermillonario.dao.interfaces.PreguntaDAO;
import quemquersermillonario.dao.interfaces.implementation.PreguntaDAOImpl;
import quemquersermillonario.dao.logica.ComprobacionText;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dto.Categoria;
import quemquersermillonario.dto.Dificultad;
import quemquersermillonario.dto.Pregunta;
import quemquersermillonario.dto.Respuesta;
import quemquersermillonario.dto.complejas.OpcionesFijas;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelCategoria;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelDificultad;

/**
 *
 * @author alvaro
 */
public class PantallaUsuarioPreguntaDatos extends javax.swing.JDialog {

    private boolean esModificacion;
    private Pregunta pregunta;
    private PreguntaDAO preguntaDAO;

    public boolean isEsModificacion() {
        return esModificacion;
    }

    public void setEsModificacion(boolean esModificacion) {
        this.esModificacion = esModificacion;
    }

    public Pregunta getPregunta() {
        return pregunta;
    }

    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }

    /**
     * Creates new form PantallaUsuarioPreguntaDatos
     *
     * @param parent
     * @param modal
     * @param esModificacion
     * @param pregunta
     */
    public PantallaUsuarioPreguntaDatos(java.awt.Frame parent, boolean modal, boolean esModificacion, Pregunta pregunta) {
        super(parent, modal);
        initComponents();
        this.esModificacion = esModificacion;
        this.preguntaDAO = new PreguntaDAOImpl();
        this.jComboBoxCategoria.setModel(ComboBoxModelCategoria.getCategoriaComboBoxModel());
        this.jComboBoxDificultad.setModel(ComboBoxModelDificultad.getDificultadComboBoxModel());
        if (esModificacion == false) {
            this.pregunta = preguntaDAO.inicializarPregunta();
            this.setTitle(Lenguaje.getString("NuevaPregunta"));

        } else {
            this.pregunta = pregunta;
            this.ObjetoACampos();
            this.setTitle(Lenguaje.getString("ActualizarPregunta"));
        }
        this.jLabelCategoria.setText(Lenguaje.getString("Categoria"));
        this.jLabelDificultad.setText(Lenguaje.getString("Dificultad"));
        this.jLabelPregunta.setText(Lenguaje.getString("Pregunta"));
        this.jLabelRespuestaCorrecta.setText(Lenguaje.getString("RespuestaCorrecta"));
        this.jLabelRespuestaIncorrecta1.setText(Lenguaje.getString("RespuestaIncorrecta"));
        this.jLabelRespuestaIncorrecta2.setText(Lenguaje.getString("RespuestaIncorrecta"));
        this.jLabelRespuestaIncorrecta3.setText(Lenguaje.getString("RespuestaIncorrecta"));
        this.jButtonAceptar.setText(Lenguaje.getString("Aceptar"));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDificultad = new javax.swing.JComboBox<>();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jTextFieldRespuesta1 = new javax.swing.JTextField();
        jLabelRespuestaCorrecta = new javax.swing.JLabel();
        jLabelPregunta = new javax.swing.JLabel();
        jTextFieldPregunta1 = new javax.swing.JTextField();
        jTextFieldRespuesta2 = new javax.swing.JTextField();
        jTextFieldRespuesta3 = new javax.swing.JTextField();
        jTextFieldRespuesta4 = new javax.swing.JTextField();
        jLabelRespuestaIncorrecta2 = new javax.swing.JLabel();
        jLabelRespuestaIncorrecta1 = new javax.swing.JLabel();
        jLabelRespuestaIncorrecta3 = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelDificultad = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldRespuesta1.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jTextFieldRespuesta1.setSelectionColor(new java.awt.Color(255, 255, 0));

        jLabelRespuestaCorrecta.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaCorrecta.setText("Respuesta Correcta:");

        jLabelPregunta.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelPregunta.setText("Pregunta:");

        jTextFieldPregunta1.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jTextFieldPregunta1.setSelectionColor(new java.awt.Color(255, 255, 0));

        jTextFieldRespuesta2.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jTextFieldRespuesta2.setSelectionColor(new java.awt.Color(255, 255, 0));

        jTextFieldRespuesta3.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jTextFieldRespuesta3.setSelectionColor(new java.awt.Color(255, 255, 0));

        jTextFieldRespuesta4.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jTextFieldRespuesta4.setSelectionColor(new java.awt.Color(255, 255, 0));

        jLabelRespuestaIncorrecta2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaIncorrecta2.setText("Respuesta Incorrecta:");

        jLabelRespuestaIncorrecta1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaIncorrecta1.setText("Respuesta Incorrecta:");

        jLabelRespuestaIncorrecta3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelRespuestaIncorrecta3.setText("Respuesta Incorrecta:");

        jLabelCategoria.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelCategoria.setText("Categoria:");

        jLabelDificultad.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelDificultad.setText("Dificultad:");

        jButtonAceptar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("ACEPTAR");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRespuestaIncorrecta1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRespuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRespuestaIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRespuestaIncorrecta3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(212, Short.MAX_VALUE)
                    .addComponent(jTextFieldPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(51, 51, 51)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespuestaCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespuestaIncorrecta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespuestaIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRespuestaIncorrecta3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButtonAceptar)
                .addGap(44, 44, 44))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jTextFieldPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if (ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta1) && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta1)
                && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta2) && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta3)
                && ComprobacionText.jTextFieldObligatorio(jTextFieldRespuesta4)) {
            if (!esModificacion) {
                camposAObjeto();
                preguntaDAO.guardar(pregunta);
                JOptionPane.showMessageDialog(this, "Pregunta registrada, gracias por colaborar.", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
            else{
                camposAObjeto();
                preguntaDAO.actualizar(pregunta);
                JOptionPane.showMessageDialog(this, "Pregunta actualizada, gracias por colaborar.", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void camposAObjeto() {
        this.pregunta.setActivo(1);
        this.pregunta.setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.setCategoria((Categoria) jComboBoxCategoria.getSelectedItem());
        this.pregunta.setDificultad((Dificultad) jComboBoxDificultad.getSelectedItem());
        this.pregunta.setUsuario(OpcionesFijas.getUsuario());
        this.pregunta.setNombre(jTextFieldPregunta1.getText());

        //Respuestas
        //Respuesta 1 Correcta
        this.pregunta.getListaRespuestas().get(0).setActivo(1);
        this.pregunta.getListaRespuestas().get(0).setCorrecta(1);
        this.pregunta.getListaRespuestas().get(0).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(0).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(0).setNombre(jTextFieldRespuesta1.getText());
        //Respuesta 2
        this.pregunta.getListaRespuestas().get(1).setActivo(1);
        this.pregunta.getListaRespuestas().get(1).setCorrecta(0);
        this.pregunta.getListaRespuestas().get(1).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(1).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(1).setNombre(jTextFieldRespuesta2.getText());
        //Respuesta 3
        this.pregunta.getListaRespuestas().get(2).setActivo(1);
        this.pregunta.getListaRespuestas().get(2).setCorrecta(0);
        this.pregunta.getListaRespuestas().get(2).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(2).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(2).setNombre(jTextFieldRespuesta3.getText());
        //Respuesta 4
        this.pregunta.getListaRespuestas().get(3).setActivo(1);
        this.pregunta.getListaRespuestas().get(3).setCorrecta(0);
        this.pregunta.getListaRespuestas().get(3).setFechaModificacion(OpcionesFijas.fechaActual());
        this.pregunta.getListaRespuestas().get(3).setPregunta(pregunta);
        this.pregunta.getListaRespuestas().get(3).setNombre(jTextFieldRespuesta4.getText());

        if (!esModificacion) {
            this.pregunta.setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(0).setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(1).setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(2).setFechaCreacion(OpcionesFijas.fechaActual());
            this.pregunta.getListaRespuestas().get(3).setFechaCreacion(OpcionesFijas.fechaActual());
        }
    }

    private void ObjetoACampos() {
        this.jTextFieldPregunta1.setText(this.pregunta.getNombre());
        int i = 0;
        for (Respuesta res : this.pregunta.getListaRespuestas()) {
            if (res.getCorrecta() == 1) {
                this.jTextFieldRespuesta1.setText(res.getNombre());
            } else {
                switch (i) {
                    case 0:
                        jTextFieldRespuesta2.setText(res.getNombre());
                        break;
                    case 1:
                        jTextFieldRespuesta3.setText(res.getNombre());
                        break;
                    case 2:
                        jTextFieldRespuesta4.setText(res.getNombre());
                        break;
                }
                i++;
            }
        }
        
        this.jComboBoxCategoria.setSelectedIndex(ComboBoxModelCategoria.getIndexOfCategoria(this.pregunta.getCategoria()));
        this.jComboBoxDificultad.setSelectedIndex(ComboBoxModelDificultad.getIndexOfDificultad(this.pregunta.getDificultad()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxDificultad;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDificultad;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelRespuestaCorrecta;
    private javax.swing.JLabel jLabelRespuestaIncorrecta1;
    private javax.swing.JLabel jLabelRespuestaIncorrecta2;
    private javax.swing.JLabel jLabelRespuestaIncorrecta3;
    private javax.swing.JTextField jTextFieldPregunta1;
    private javax.swing.JTextField jTextFieldRespuesta1;
    private javax.swing.JTextField jTextFieldRespuesta2;
    private javax.swing.JTextField jTextFieldRespuesta3;
    private javax.swing.JTextField jTextFieldRespuesta4;
    // End of variables declaration//GEN-END:variables
}
