/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.formulario;

import java.awt.Frame;
import java.io.File;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Popup;
import quemquersermillonario.dao.interfaces.FormularioDAO;
import quemquersermillonario.dao.interfaces.implementation.FormularioDAOImpl;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.LogicaFormularios;
import quemquersermillonario.dao.logica.VentanasLogica;
import quemquersermillonario.dto.Formulario;
import quemquersermillonario.gui.tablemodels.UsuarioFormulariosTableModel;

/**
 *
 * @author alvaro
 */
public class PantallaFormularioUsuario extends javax.swing.JDialog {

    /**
     * Creates new form PantallaFormularioUsuario
     */
    private Frame parent;
    private Popup popup;
    private List<Formulario> listaFormularios;
    private FormularioDAO fdao = new FormularioDAOImpl();

    public PantallaFormularioUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        VentanasLogica.estilizarVentaja(this);
        this.setTitle(Lenguaje.getString("MisFormularios"));
        rellenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFormularios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonAniadir = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableFormularios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFormularios);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jButtonAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/aniadir_pregunta_normal_min.png"))); // NOI18N
        jButtonAniadir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/aniadir_pregunta_clicado_min.png"))); // NOI18N
        jButtonAniadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAniadir);
        jButtonAniadir.getAccessibleContext().setAccessibleName("Aniadir");

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/modificar_pregunta_normal_min.png"))); // NOI18N
        jButtonModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/modificar_pregunta_clicado_min.png"))); // NOI18N
        jButtonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar);
        jButtonModificar.getAccessibleContext().setAccessibleName("Modificar");

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/eliminar_normal_min.png"))); // NOI18N
        jButtonEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/eliminar_clicado_min.png"))); // NOI18N
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar);
        jButtonEliminar.getAccessibleContext().setAccessibleName("Eliminar");

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/imprimir_normal_min.png"))); // NOI18N
        jButtonImprimir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/imprimir_clicado_min.png"))); // NOI18N
        jButtonImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonImprimir);
        jButtonImprimir.getAccessibleContext().setAccessibleName("Imprimir");

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/salir_normal_min.png"))); // NOI18N
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/min/salir_clicado_min.png"))); // NOI18N
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);
        jButtonSalir.getAccessibleContext().setAccessibleName("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirActionPerformed
        // TODO add your handling code here:
        popup.hide();
        PantallaFormularioDatos pfd = new PantallaFormularioDatos(parent, true, false, null);
        pfd.setVisible(true);
        rellenarTabla();
    }//GEN-LAST:event_jButtonAniadirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        popup.hide();
        if (jTableFormularios.getSelectedRow() >= 0) {
            int opc = JOptionPane.showConfirmDialog(this, Lenguaje.getString("Confirmacion.Eliminar"), Lenguaje.getString("Confirmacion"), JOptionPane.YES_NO_OPTION);
            if (opc == JOptionPane.OK_OPTION) {
                this.fdao.borrar(this.listaFormularios.get(jTableFormularios.getSelectedRow()));
                rellenarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, Lenguaje.getString("SeleccionarFormulario"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void ratonEntra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonEntra
        // TODO add your handling code here:
        JButton jb = (JButton) evt.getSource();
        popup = VentanasLogica.mensajePopup(popup, jb.getAccessibleContext().getAccessibleName(), evt);
        popup.show();

    }//GEN-LAST:event_ratonEntra

    private void ratonSale(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonSale
        // TODO add your handling code here:
        popup.hide();
    }//GEN-LAST:event_ratonSale

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        popup.hide();
        if (jTableFormularios.getSelectedRow() >= 0) {
            Formulario f = this.listaFormularios.get(jTableFormularios.getSelectedRow());
            System.out.println(f.getIdFormulario() + " " + f.getNombre() + " " + f.getListaPreguntas().size());
            PantallaFormularioDatos pfd = new PantallaFormularioDatos(parent, true, true, f);
            pfd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Lenguaje.getString("SeleccionarFormulario"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:

        if (jTableFormularios.getSelectedRow() >= 0) {
            try {
                Formulario f = listaFormularios.get(jTableFormularios.getSelectedRow());
                if (!LogicaFormularios.generarFormulariosTest(f)) {
                    JOptionPane.showMessageDialog(this, Lenguaje.getString("ErrorImprimir"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, Lenguaje.getString("Impreso") + new File("").getAbsolutePath(), Lenguaje.getString("Imprimir"), JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, Lenguaje.getString("SeleccionarFormulario"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButtonImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    private void rellenarTabla() {
        this.listaFormularios = fdao.getListaFormulariosActivos();
        UsuarioFormulariosTableModel uftm = new UsuarioFormulariosTableModel(listaFormularios);
        jTableFormularios.setModel(uftm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAniadir;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFormularios;
    // End of variables declaration//GEN-END:variables
}
