/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.comodines;

import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import quemquersermillonario.dao.interfaces.UsuarioComodinesDAO;
import quemquersermillonario.dao.interfaces.implementation.UsuarioComodinesDAOImpl;
import quemquersermillonario.dao.interfaces.implementation.UsuarioDAOImpl;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.VentanasLogica;
import quemquersermillonario.dto.Comodin;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelComodin;

/**
 *
 * @author alvaro
 */
public class PantallaComprarComodines extends javax.swing.JDialog {

    /**
     * Creates new form PantallaComprarComodines
     */
    private int puntosUsuario;
    private Comodin comodin;
    private UsuarioDAOImpl usuarioDAOImpl = new UsuarioDAOImpl();

    public PantallaComprarComodines(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refrescar();
        this.setTitle(Lenguaje.getString("TiendaComodines"));
        this.jButtonComprar.setText(Lenguaje.getString("Comprar"));
        this.jLabelTienes.setText(Lenguaje.getString("Tienes"));
        this.jLabelPrecio.setText(Lenguaje.getString("Precio"));
        VentanasLogica.estilizarVentaja(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxComodines = new javax.swing.JComboBox<>();
        jLabelValorComodin = new javax.swing.JLabel();
        jLabelPuntosUsuario = new javax.swing.JLabel();
        jButtonComprar = new javax.swing.JButton();
        jLabelPrecio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTienes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxComodines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxComodines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComodinesActionPerformed(evt);
            }
        });

        jLabelPuntosUsuario.setText("jLabel1");

        jButtonComprar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonComprar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComprar.setText("COMPRAR");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });

        jLabelPrecio.setText("Precio");

        jLabel2.setText("Tienes");

        jLabelTienes.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabelPuntosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxComodines, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabelValorComodin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabelTienes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelPuntosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxComodines, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorComodin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTienes, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxComodinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComodinesActionPerformed
        // TODO add your handling code here:
         comodin = (Comodin) jComboBoxComodines.getSelectedItem();
        cambiarPrecio(comodin);
        cambiarHay(comodin);
    }//GEN-LAST:event_jComboBoxComodinesActionPerformed

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        if (puntosUsuario >= comodin.getCoste()) {
            UsuarioComodinesDAO  uc = new UsuarioComodinesDAOImpl();
            uc.comprar(comodin);       
            JOptionPane.showMessageDialog(this, " Ha comprado " + comodin.getNombre(), " compra ", JOptionPane.INFORMATION_MESSAGE);
            refrescar();
        } else {
            JOptionPane.showMessageDialog(this, "No dispone de puntos suficientes ", "SIN PUNTOS", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonComprarActionPerformed

    private void refrescar() {
        puntosUsuario = usuarioDAOImpl.puntosUsuario();
        jComboBoxComodines.setModel(ComboBoxModelComodin.getCategoriaComboBoxModel());
        comodin = (Comodin) jComboBoxComodines.getSelectedItem();
        cambiarPrecio(comodin);
        jLabelPuntosUsuario.setText("Tienes " + puntosUsuario + " puntos disponibles");
        cambiarHay(comodin);
        
    }

    private void cambiarPrecio(Comodin cmd) {
        jLabelValorComodin.setText(Integer.toString(cmd.getCoste()));
    }
    
    private void cambiarHay(Comodin cmd){
        UsuarioComodinesDAOImpl usaComodinesDAOImpl = new UsuarioComodinesDAOImpl();
        int hay = usaComodinesDAOImpl.comodinesActivos(cmd);
        jLabelTienes.setText(Integer.toString(hay));
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JComboBox<String> jComboBoxComodines;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPuntosUsuario;
    private javax.swing.JLabel jLabelTienes;
    private javax.swing.JLabel jLabelValorComodin;
    // End of variables declaration//GEN-END:variables
}
