/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.partida;

import java.awt.Frame;
import quemquersermillonario.dao.interfaces.ModoJuegoDAO;
import quemquersermillonario.dao.interfaces.implementation.ModoJuegoDAOImpl;
import quemquersermillonario.dto.ModoJuego;

/**
 *
 * @author alvaro
 */
public class PantallaSeleccionJuego extends javax.swing.JDialog {

    /**
     * Creates new form PantallaSeleccionJuego
     */
    
    private Frame parent;
    public PantallaSeleccionJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNormal = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonSupervivencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonNormal.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNormal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNormal.setText("NORMAL");
        jButtonNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNormalActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonSupervivencia.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSupervivencia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupervivencia.setText("SUPERVIVENCIA");
        jButtonSupervivencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupervivenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSupervivencia, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jButtonNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jButtonSupervivencia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNormalActionPerformed
        ModoJuegoDAO mjdao = new ModoJuegoDAOImpl();
        ModoJuego mj = mjdao.buscarModoJuego("NORMAL");
        PantallaResponderPregunta prp = new PantallaResponderPregunta(parent, true, mj);
        prp.setVisible(true);
    }//GEN-LAST:event_jButtonNormalActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSupervivenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupervivenciaActionPerformed
        // TODO add your handling code here:
        PantallaSeleccionCategoriaDificultad pscd = new PantallaSeleccionCategoriaDificultad(parent,true);
        pscd.setVisible(true);
    }//GEN-LAST:event_jButtonSupervivenciaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNormal;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSupervivencia;
    // End of variables declaration//GEN-END:variables
}
