/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.partida;

import java.awt.Frame;
import quemquersermillonario.dao.interfaces.ModoJuegoDAO;
import quemquersermillonario.dao.interfaces.implementation.ModoJuegoDAOImpl;
import quemquersermillonario.dao.logica.PartidaJugando;
import quemquersermillonario.dto.Categoria;
import quemquersermillonario.dto.Dificultad;
import quemquersermillonario.dto.ModoJuego;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelCategoria;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelDificultad;

/**
 *
 * @author alvaro
 */
public class PantallaSeleccionCategoriaDificultad extends javax.swing.JDialog {

    /**
     * Creates new form PantallaSeleccionCategoriaDificultad
     */
    private Frame parent;

    public PantallaSeleccionCategoriaDificultad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jComboBoxCategoria.setModel(ComboBoxModelCategoria.getCategoriaWithDefaultComboBoxModel());
        this.jComboBoxDificultad.setModel(ComboBoxModelDificultad.getDificultadWithDefaultComboBoxModel());
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxDificultad = new javax.swing.JComboBox<>();
        jButtonJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonJugar.setText("JUGAR");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxDificultad, 0, 167, Short.MAX_VALUE)
                        .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jComboBoxDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
        PartidaJugando.categoria = (Categoria) jComboBoxCategoria.getSelectedItem();
        PartidaJugando.dificultad = (Dificultad) jComboBoxDificultad.getSelectedItem();
        ModoJuegoDAO mjdao = new ModoJuegoDAOImpl();
        ModoJuego mj = mjdao.buscarModoJuego("SUPERVIVENCIA");
        PantallaResponderPregunta prp = new PantallaResponderPregunta(parent, true, mj);
        prp.setVisible(true);
    }//GEN-LAST:event_jButtonJugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxDificultad;
    // End of variables declaration//GEN-END:variables
}
