/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.partida;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Popup;
import quemquersermillonario.dao.interfaces.UsuarioComodinesDAO;
import quemquersermillonario.dao.interfaces.implementation.UsuarioComodinesDAOImpl;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.PartidaJugando;
import quemquersermillonario.dao.logica.VentanasLogica;
import quemquersermillonario.dto.Comodin;
import quemquersermillonario.dto.ModoJuego;
import quemquersermillonario.dto.Pregunta;
import quemquersermillonario.dto.RespuestaUsuario;

/**
 *
 * @author alvaro
 */
public class PantallaResponderPregunta extends javax.swing.JDialog {

    /**
     * Creates new form PantallaResponderPregunta
     *
     * @param parent
     * @param modal
     * @param modoJuego
     */
    private int ronda = 0;
    private Pregunta pregunta;
    private UsuarioComodinesDAO ucdao = new UsuarioComodinesDAOImpl();
    private Popup popup;
    
    public PantallaResponderPregunta(java.awt.Frame parent, boolean modal, ModoJuego modoJuego) {
        super(parent, modal);
        initComponents();
        PartidaJugando.inicializarPartida(modoJuego);
        colocarPregunta();
        this.setTitle(Lenguaje.getString("Jugando"));
        this.jLabelPuntosPartidaActualTexto.setText(Lenguaje.getString("Puntos.Conseguidos.Partida"));
        this.jLabelRondalTexto1.setText(Lenguaje.getString("Ronda"));
        VentanasLogica.estilizarVentaja(this);
        if (modoJuego.getIdModoJuego() == 2) {
            jLabelRonda10.setText("/10");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPregunta = new javax.swing.JLabel();
        jLabelPuntuacionPartida = new javax.swing.JLabel();
        jLabelTotalPreguntas = new javax.swing.JLabel();
        jButton50Porciento = new javax.swing.JButton();
        jButtonCambioPregunta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonRespuesta1 = new javax.swing.JButton();
        jButtonRespuesta2 = new javax.swing.JButton();
        jButtonRespuesta4 = new javax.swing.JButton();
        jButtonRespuesta3 = new javax.swing.JButton();
        jLabelPuntosPartidaActualTexto = new javax.swing.JLabel();
        jLabelRondalTexto1 = new javax.swing.JLabel();
        jLabelRonda10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelPregunta.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPregunta.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabelPregunta.setText("jLabel1");

        jLabelPuntuacionPartida.setText("jLabel1");

        jLabelTotalPreguntas.setText("jLabel1");

        jButton50Porciento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/50_normal.png"))); // NOI18N
        jButton50Porciento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/50_clicado.png"))); // NOI18N
        jButton50Porciento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButton50Porciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50PorcientoActionPerformed(evt);
            }
        });

        jButtonCambioPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/cambio_pregunta_normal.png"))); // NOI18N
        jButtonCambioPregunta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/cambio_pregunta_clicado.png"))); // NOI18N
        jButtonCambioPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonCambioPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambioPreguntaActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jButtonRespuesta1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButtonRespuesta1.setText("jButton1");
        jButtonRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRespuesta1);

        jButtonRespuesta2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButtonRespuesta2.setText("jButton1");
        jButtonRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRespuesta2);

        jButtonRespuesta4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButtonRespuesta4.setText("jButton1");
        jButtonRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRespuesta4);

        jButtonRespuesta3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jButtonRespuesta3.setText("jButton1");
        jButtonRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRespuesta3);

        jLabelPuntosPartidaActualTexto.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabelPuntosPartidaActualTexto.setText("jLabel1");

        jLabelRondalTexto1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabelRondalTexto1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton50Porciento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                        .addComponent(jButtonCambioPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPuntosPartidaActualTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPuntuacionPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelRondalTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelTotalPreguntas)
                                .addGap(1, 1, 1)
                                .addComponent(jLabelRonda10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPuntuacionPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPuntosPartidaActualTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRonda10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRondalTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotalPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCambioPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50Porciento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton50Porciento.getAccessibleContext().setAccessibleName("50Porciento");
        jButtonCambioPregunta.getAccessibleContext().setAccessibleName("CambioPregunta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta1ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(0));
    }//GEN-LAST:event_jButtonRespuesta1ActionPerformed

    private void jButtonRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta2ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(1));
    }//GEN-LAST:event_jButtonRespuesta2ActionPerformed

    private void jButtonRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta3ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(2));
    }//GEN-LAST:event_jButtonRespuesta3ActionPerformed

    private void jButtonRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta4ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(3));
    }//GEN-LAST:event_jButtonRespuesta4ActionPerformed

    private void jButton50PorcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50PorcientoActionPerformed
        // TODO add your handling code here:    
        popup.hide();
        comodin50();
        Comodin comodin = new Comodin();
        comodin.setIdComodin(1);
        ucdao.utilizarComodin(comodin);
        jButton50Porciento.setEnabled(false);

    }//GEN-LAST:event_jButton50PorcientoActionPerformed

    private void jButtonCambioPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambioPreguntaActionPerformed
        // TODO add your handling code here:
        popup.hide();
        cambiarPregunta();
        Comodin comodin = new Comodin();
        comodin.setIdComodin(2);
        ucdao.utilizarComodin(comodin);
        jButtonCambioPregunta.setEnabled(false);
    }//GEN-LAST:event_jButtonCambioPreguntaActionPerformed

    private void ratonEntra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonEntra
        // TODO add your handling code here:
        JButton jb = (JButton) evt.getSource();
        popup = VentanasLogica.mensajePopup(popup, jb.getAccessibleContext().getAccessibleName(), evt);
        popup.show();
    }//GEN-LAST:event_ratonEntra

    private void ratonSale(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonSale
        // TODO add your handling code here:
        popup.hide();
    }//GEN-LAST:event_ratonSale

    /**
     * @param args the command line arguments
     */
    public void colocarPregunta() {
        try {
            cambiarPregunta();
            jLabelPuntuacionPartida.setText(Integer.toString(PartidaJugando.partida.getPuntuacion()));
            ronda++;
            jLabelTotalPreguntas.setText(Integer.toString(ronda));
            resetearRespuestas();
            resetearComodines();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, Lenguaje.getString("NoMasPreguntas"), Lenguaje.getString("FinPartida"), JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }
    
    private void cambiarPregunta() {
        this.pregunta = PartidaJugando.seleccionarPregunta();
        jLabelPregunta.setText(this.pregunta.getNombre());
        jButtonRespuesta1.setText(this.pregunta.getListaRespuestas().get(0).getNombre());
        jButtonRespuesta2.setText(this.pregunta.getListaRespuestas().get(1).getNombre());
        jButtonRespuesta3.setText(this.pregunta.getListaRespuestas().get(2).getNombre());
        jButtonRespuesta4.setText(this.pregunta.getListaRespuestas().get(3).getNombre());
        resetearRespuestas();
        
    }
    
    private void avanceJuego(Boolean acierto) {
        if (acierto) {
            
            if (PartidaJugando.partida.getModoJuego().getIdModoJuego() == 2 && ronda == 10) {
                JOptionPane.showMessageDialog(this, Lenguaje.getString("Enhorabuena.Ganador"), Lenguaje.getString("Ganador"), JOptionPane.INFORMATION_MESSAGE);
                PartidaJugando.partidaGanada();
                this.setVisible(false);
            } else {
                int opc = JOptionPane.showConfirmDialog(this, Lenguaje.getString("Acierto.contiuar.pregunta"), Lenguaje.getString("Acierto"), JOptionPane.YES_NO_OPTION);
                if (opc == JOptionPane.YES_OPTION) {
                    colocarPregunta();
                } else {
                    JOptionPane.showMessageDialog(this, Lenguaje.getString("Gracias.jugar"), Lenguaje.getString("Plantado"), JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, Lenguaje.getString("Fallo"), Lenguaje.getString("Error"), JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }
    
    private boolean responder(int elegida) {
        RespuestaUsuario respuestaUsuario = new RespuestaUsuario();
        respuestaUsuario.setPartida(PartidaJugando.partida);
        respuestaUsuario.setPregunta(this.pregunta);
        return PartidaJugando.comprobarRespuesta(respuestaUsuario, elegida);
    }
    
    private void comodin50() {
        List<Integer> listaCorrecta = PartidaJugando.usarComodin50(pregunta);
        if (!listaCorrecta.contains(0)) {
            jButtonRespuesta1.setEnabled(false);
        }
        if (!listaCorrecta.contains(1)) {
            jButtonRespuesta2.setEnabled(false);
        }
        if (!listaCorrecta.contains(2)) {
            jButtonRespuesta3.setEnabled(false);
        }
        if (!listaCorrecta.contains(3)) {
            jButtonRespuesta4.setEnabled(false);
        }
    }
    
    private void resetearRespuestas() {
        jButtonRespuesta1.setEnabled(true);
        jButtonRespuesta2.setEnabled(true);
        jButtonRespuesta3.setEnabled(true);
        jButtonRespuesta4.setEnabled(true);
        resetearComodines();
    }
    
    private void resetearComodines() {
        if (PartidaJugando.tieneComodines50()) {
            jButton50Porciento.setEnabled(true);
        } else {
            jButton50Porciento.setEnabled(false);
        }
        if (PartidaJugando.tieneComodinesCambio()) {
            jButtonCambioPregunta.setEnabled(true);
        } else {
            jButtonCambioPregunta.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton50Porciento;
    private javax.swing.JButton jButtonCambioPregunta;
    private javax.swing.JButton jButtonRespuesta1;
    private javax.swing.JButton jButtonRespuesta2;
    private javax.swing.JButton jButtonRespuesta3;
    private javax.swing.JButton jButtonRespuesta4;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelPuntosPartidaActualTexto;
    private javax.swing.JLabel jLabelPuntuacionPartida;
    private javax.swing.JLabel jLabelRonda10;
    private javax.swing.JLabel jLabelRondalTexto1;
    private javax.swing.JLabel jLabelTotalPreguntas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
