/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.partida;

import javax.swing.JOptionPane;
import quemquersermillonario.dao.logica.PartidaJugando;
import quemquersermillonario.dto.ModoJuego;
import quemquersermillonario.dto.Pregunta;
import quemquersermillonario.dto.RespuestaUsuario;
import quemquersermillonario.dto.complejas.OpcionesFijas;

/**
 *
 * @author alvaro
 */
public class PantallaResponderPregunta extends javax.swing.JDialog {

    /**
     * Creates new form PantallaResponderPregunta
     *
     * @param parent
     * @param modal
     * @param modoJuego
     */
    private int ronda = 0;
    private Pregunta pregunta;

    public PantallaResponderPregunta(java.awt.Frame parent, boolean modal, ModoJuego modoJuego) {
        super(parent, modal);
        initComponents();
        PartidaJugando.inicializarPartida(modoJuego);
        colocarPregunta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPregunta = new javax.swing.JLabel();
        jButtonRespuesta1 = new javax.swing.JButton();
        jButtonRespuesta2 = new javax.swing.JButton();
        jButtonRespuesta3 = new javax.swing.JButton();
        jButtonRespuesta4 = new javax.swing.JButton();
        jLabelPuntuacionPartida = new javax.swing.JLabel();
        jLabelTotalPreguntas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelPregunta.setText("jLabel1");

        jButtonRespuesta1.setText("jButton1");
        jButtonRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta1ActionPerformed(evt);
            }
        });

        jButtonRespuesta2.setText("jButton1");
        jButtonRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta2ActionPerformed(evt);
            }
        });

        jButtonRespuesta3.setText("jButton1");
        jButtonRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta3ActionPerformed(evt);
            }
        });

        jButtonRespuesta4.setText("jButton1");
        jButtonRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta4ActionPerformed(evt);
            }
        });

        jLabelPuntuacionPartida.setText("jLabel1");

        jLabelTotalPreguntas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRespuesta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRespuesta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jButtonRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPuntuacionPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabelTotalPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelPuntuacionPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotalPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButtonRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jButtonRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta1ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(0));
    }//GEN-LAST:event_jButtonRespuesta1ActionPerformed

    private void jButtonRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta2ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(1));
    }//GEN-LAST:event_jButtonRespuesta2ActionPerformed

    private void jButtonRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta3ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(2));
    }//GEN-LAST:event_jButtonRespuesta3ActionPerformed

    private void jButtonRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta4ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(3));
    }//GEN-LAST:event_jButtonRespuesta4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void colocarPregunta() {
        this.pregunta = PartidaJugando.seleccionarPregunta();
        jLabelPregunta.setText(this.pregunta.getNombre());
        jButtonRespuesta1.setText(this.pregunta.getListaRespuestas().get(0).getNombre());
        jButtonRespuesta2.setText(this.pregunta.getListaRespuestas().get(1).getNombre());
        jButtonRespuesta3.setText(this.pregunta.getListaRespuestas().get(2).getNombre());
        jButtonRespuesta4.setText(this.pregunta.getListaRespuestas().get(3).getNombre());
        jLabelPuntuacionPartida.setText(Integer.toString(PartidaJugando.partida.getPuntuacion()));
        ronda++;
        jLabelTotalPreguntas.setText(Integer.toString(ronda));
    }

    private void avanceJuego(Boolean acierto) {
        if (acierto) {
            int opc = JOptionPane.showConfirmDialog(this, "Pregunta acertada, desea continuar?", "Acierto", JOptionPane.INFORMATION_MESSAGE);
            if (opc == JOptionPane.YES_OPTION) {
                colocarPregunta();
            } else {
                JOptionPane.showMessageDialog(this, "Gracias por jugar", "Plantado", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ha fallado", "Plantado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }

    private boolean responder(int elegida) {
        RespuestaUsuario respuestaUsuario = new RespuestaUsuario();
        respuestaUsuario.setPartida(PartidaJugando.partida);
        respuestaUsuario.setPregunta(this.pregunta);
        return PartidaJugando.comprobarRespuesta(respuestaUsuario, elegida);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRespuesta1;
    private javax.swing.JButton jButtonRespuesta2;
    private javax.swing.JButton jButtonRespuesta3;
    private javax.swing.JButton jButtonRespuesta4;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelPuntuacionPartida;
    private javax.swing.JLabel jLabelTotalPreguntas;
    // End of variables declaration//GEN-END:variables
}
