/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.partida;

import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import quemquersermillonario.dao.interfaces.UsuarioComodinesDAO;
import quemquersermillonario.dao.interfaces.implementation.UsuarioComodinesDAOImpl;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.PartidaJugando;
import quemquersermillonario.dto.Comodin;
import quemquersermillonario.dto.ModoJuego;
import quemquersermillonario.dto.Pregunta;
import quemquersermillonario.dto.RespuestaUsuario;
import quemquersermillonario.dto.complejas.OpcionesFijas;

/**
 *
 * @author alvaro
 */
public class PantallaResponderPregunta extends javax.swing.JDialog {

    /**
     * Creates new form PantallaResponderPregunta
     *
     * @param parent
     * @param modal
     * @param modoJuego
     */
    private int ronda = 0;
    private Pregunta pregunta;
    private UsuarioComodinesDAO ucdao = new UsuarioComodinesDAOImpl();

    public PantallaResponderPregunta(java.awt.Frame parent, boolean modal, ModoJuego modoJuego) {
        super(parent, modal);
        initComponents();
        PartidaJugando.inicializarPartida(modoJuego);
        colocarPregunta();
        this.setTitle(Lenguaje.getString("Jugando"));
        this.jButton50Porciento.setText(Lenguaje.getString("50Porciento"));
        this.jButtonCambioPregunta.setText(Lenguaje.getString("CambioPregunta"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPregunta = new javax.swing.JLabel();
        jButtonRespuesta1 = new javax.swing.JButton();
        jButtonRespuesta2 = new javax.swing.JButton();
        jButtonRespuesta3 = new javax.swing.JButton();
        jButtonRespuesta4 = new javax.swing.JButton();
        jLabelPuntuacionPartida = new javax.swing.JLabel();
        jLabelTotalPreguntas = new javax.swing.JLabel();
        jButton50Porciento = new javax.swing.JButton();
        jButtonCambioPregunta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelPregunta.setText("jLabel1");

        jButtonRespuesta1.setText("jButton1");
        jButtonRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta1ActionPerformed(evt);
            }
        });

        jButtonRespuesta2.setText("jButton1");
        jButtonRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta2ActionPerformed(evt);
            }
        });

        jButtonRespuesta3.setText("jButton1");
        jButtonRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta3ActionPerformed(evt);
            }
        });

        jButtonRespuesta4.setText("jButton1");
        jButtonRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespuesta4ActionPerformed(evt);
            }
        });

        jLabelPuntuacionPartida.setText("jLabel1");

        jLabelTotalPreguntas.setText("jLabel1");

        jButton50Porciento.setText("50 %");
        jButton50Porciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50PorcientoActionPerformed(evt);
            }
        });

        jButtonCambioPregunta.setText("Cambio Pregunta");
        jButtonCambioPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambioPreguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRespuesta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRespuesta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jButtonRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPuntuacionPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabelTotalPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton50Porciento, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jButtonCambioPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelPuntuacionPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotalPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButtonRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jButtonRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton50Porciento, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCambioPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta1ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(0));
    }//GEN-LAST:event_jButtonRespuesta1ActionPerformed

    private void jButtonRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta2ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(1));
    }//GEN-LAST:event_jButtonRespuesta2ActionPerformed

    private void jButtonRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta3ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(2));
    }//GEN-LAST:event_jButtonRespuesta3ActionPerformed

    private void jButtonRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespuesta4ActionPerformed
        // TODO add your handling code here:
        avanceJuego(responder(3));
    }//GEN-LAST:event_jButtonRespuesta4ActionPerformed

    private void jButton50PorcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50PorcientoActionPerformed
        // TODO add your handling code here:
        comodin50();
        Comodin comodin = new Comodin();
        comodin.setIdComodin(1);
        ucdao.utilizarComodin(comodin);
        jButton50Porciento.setEnabled(false);

    }//GEN-LAST:event_jButton50PorcientoActionPerformed

    private void jButtonCambioPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambioPreguntaActionPerformed
        // TODO add your handling code here:
        cambiarPregunta();
        Comodin comodin = new Comodin();
        comodin.setIdComodin(2);
        ucdao.utilizarComodin(comodin);
        jButtonCambioPregunta.setEnabled(false);
    }//GEN-LAST:event_jButtonCambioPreguntaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void colocarPregunta() {
        try {
            cambiarPregunta();
            jLabelPuntuacionPartida.setText(Integer.toString(PartidaJugando.partida.getPuntuacion()));
            ronda++;
            jLabelTotalPreguntas.setText(Integer.toString(ronda));
            resetearRespuestas();
            resetearComodines();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No hay mas preguntas relacionadas", "Fin partida", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }

    private void cambiarPregunta() {
        this.pregunta = PartidaJugando.seleccionarPregunta();
        jLabelPregunta.setText(this.pregunta.getNombre());
        jButtonRespuesta1.setText(this.pregunta.getListaRespuestas().get(0).getNombre());
        jButtonRespuesta2.setText(this.pregunta.getListaRespuestas().get(1).getNombre());
        jButtonRespuesta3.setText(this.pregunta.getListaRespuestas().get(2).getNombre());
        jButtonRespuesta4.setText(this.pregunta.getListaRespuestas().get(3).getNombre());
        resetearRespuestas();

    }

    private void avanceJuego(Boolean acierto) {
        if (acierto) {

            if (PartidaJugando.partida.getModoJuego().getIdModoJuego() == 2 && ronda == 10) {
                JOptionPane.showMessageDialog(this, "Enhorabuena ha ganado", "GANADOR", JOptionPane.INFORMATION_MESSAGE);
                PartidaJugando.partidaGanada();
                this.setVisible(false);
            } else {
                int opc = JOptionPane.showConfirmDialog(this, "Pregunta acertada, desea continuar?", "Acierto", JOptionPane.INFORMATION_MESSAGE);
                if (opc == JOptionPane.YES_OPTION) {
                    colocarPregunta();
                } else {
                    JOptionPane.showMessageDialog(this, "Gracias por jugar", "Plantado", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ha fallado", "Plantado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
    }

    private boolean responder(int elegida) {
        RespuestaUsuario respuestaUsuario = new RespuestaUsuario();
        respuestaUsuario.setPartida(PartidaJugando.partida);
        respuestaUsuario.setPregunta(this.pregunta);
        return PartidaJugando.comprobarRespuesta(respuestaUsuario, elegida);
    }

    private void comodin50() {
        List<Integer> listaCorrecta = PartidaJugando.usarComodin50(pregunta);
        if (!listaCorrecta.contains(0)) {
            jButtonRespuesta1.setEnabled(false);
        }
        if (!listaCorrecta.contains(1)) {
            jButtonRespuesta2.setEnabled(false);
        }
        if (!listaCorrecta.contains(2)) {
            jButtonRespuesta3.setEnabled(false);
        }
        if (!listaCorrecta.contains(3)) {
            jButtonRespuesta4.setEnabled(false);
        }
    }

    private void resetearRespuestas() {
        jButtonRespuesta1.setEnabled(true);
        jButtonRespuesta2.setEnabled(true);
        jButtonRespuesta3.setEnabled(true);
        jButtonRespuesta4.setEnabled(true);
        resetearComodines();
    }

    private void resetearComodines() {
        if (PartidaJugando.tieneComodines50()) {
            jButton50Porciento.setEnabled(true);
        } else {
            jButton50Porciento.setEnabled(false);
        }
        if (PartidaJugando.tieneComodinesCambio()) {
            jButtonCambioPregunta.setEnabled(true);
        } else {
            jButtonCambioPregunta.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton50Porciento;
    private javax.swing.JButton jButtonCambioPregunta;
    private javax.swing.JButton jButtonRespuesta1;
    private javax.swing.JButton jButtonRespuesta2;
    private javax.swing.JButton jButtonRespuesta3;
    private javax.swing.JButton jButtonRespuesta4;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelPuntuacionPartida;
    private javax.swing.JLabel jLabelTotalPreguntas;
    // End of variables declaration//GEN-END:variables
}
