/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.partida;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.Popup;
import quemquersermillonario.dao.interfaces.ModoJuegoDAO;
import quemquersermillonario.dao.interfaces.implementation.ModoJuegoDAOImpl;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.VentanasLogica;
import quemquersermillonario.dto.ModoJuego;

/**
 *
 * @author alvaro
 */
public class PantallaSeleccionJuego extends javax.swing.JDialog {

    /**
     * Creates new form PantallaSeleccionJuego
     */
    
    private Frame parent;
    private Popup popup;
    public PantallaSeleccionJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.setTitle(Lenguaje.getString("ModoJuegos"));
        VentanasLogica.estilizarVentaja(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSupervivencia = new javax.swing.JButton();
        jButtonNormal = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        jButtonSupervivencia.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSupervivencia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupervivencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/infinito_normal.png"))); // NOI18N
        jButtonSupervivencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/infinito_clicado.png"))); // NOI18N
        jButtonSupervivencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonSupervivencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupervivenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSupervivencia);
        jButtonSupervivencia.getAccessibleContext().setAccessibleName("Supervivencia");

        jButtonNormal.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNormal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/jugar_normal_1.png"))); // NOI18N
        jButtonNormal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/jugar_clicadol_1.png"))); // NOI18N
        jButtonNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNormalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNormal);
        jButtonNormal.getAccessibleContext().setAccessibleName("Normal");

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_normal.png"))); // NOI18N
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_clicado.png"))); // NOI18N
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);
        jButtonSalir.getAccessibleContext().setAccessibleName("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNormalActionPerformed
       popup.hide();
        ModoJuegoDAO mjdao = new ModoJuegoDAOImpl();
        ModoJuego mj = mjdao.buscarModoJuego("NORMAL");
        PantallaResponderPregunta prp = new PantallaResponderPregunta(parent, true, mj);
        prp.setVisible(true);
    }//GEN-LAST:event_jButtonNormalActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSupervivenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupervivenciaActionPerformed
        // TODO add your handling code here:
        popup.hide();
        PantallaSeleccionCategoriaDificultad pscd = new PantallaSeleccionCategoriaDificultad(parent,true);
        pscd.setVisible(true);
    }//GEN-LAST:event_jButtonSupervivenciaActionPerformed

    private void ratonEntra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonEntra
        // TODO add your handling code here:
        JButton jb = (JButton) evt.getSource();
        popup = VentanasLogica.mensajePopup(popup, jb.getAccessibleContext().getAccessibleName(), evt);
        popup.show();
    }//GEN-LAST:event_ratonEntra

    private void ratonSale(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonSale
        // TODO add your handling code here:
        popup.hide();
    }//GEN-LAST:event_ratonSale

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNormal;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSupervivencia;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
