/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.usuario;

import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.Popup;
import quemquersermillonario.dao.interfaces.GenericDAO;
import quemquersermillonario.dao.interfaces.UsuarioDAO;
import quemquersermillonario.dao.interfaces.implementation.UsuarioDAOImpl;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.OpcionesFijasLogica;
import quemquersermillonario.dao.logica.VentanasLogica;
import quemquersermillonario.dto.Usuario;
import quemquersermillonario.dto.complejas.OpcionesFijas;
import quemquersermillonario.gui.comodines.PantallaComprarComodines;
import quemquersermillonario.gui.partida.PantallaSeleccionJuego;
import quemquersermillonario.gui.usuario.preguntas.PantallaUsuarioPreguntas;

/**
 *
 * @author alvaro
 */
public class PantallaUsuarioOpciones extends javax.swing.JDialog {

    /**
     * Creates new form PantallaUsuarioOpciones
     */
    private Frame parent;
    private Popup popup;

    public PantallaUsuarioOpciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.setTitle(Lenguaje.getString("MenuPrincipal"));
        VentanasLogica.estilizarVentaja(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonActualizar = new javax.swing.JButton();
        jButtonMisPreguntas = new javax.swing.JButton();
        jButtonJugar = new javax.swing.JButton();
        jButtonTienda = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 0, 5));

        jButtonActualizar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/mis_datos_normal.png"))); // NOI18N
        jButtonActualizar.setToolTipText("");
        jButtonActualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/mis_datos_clicado.png"))); // NOI18N
        jButtonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonActualizar);
        jButtonActualizar.getAccessibleContext().setAccessibleName("mis_datos");

        jButtonMisPreguntas.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMisPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMisPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/mis_preguntas_normal.png"))); // NOI18N
        jButtonMisPreguntas.setToolTipText("");
        jButtonMisPreguntas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/mis_preguntas_clicado.png"))); // NOI18N
        jButtonMisPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonMisPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisPreguntasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMisPreguntas);
        jButtonMisPreguntas.getAccessibleContext().setAccessibleName("mis_preguntas");

        jButtonJugar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonJugar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/jugar_normal.png"))); // NOI18N
        jButtonJugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/jugar_clicado.png"))); // NOI18N
        jButtonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonJugar);
        jButtonJugar.getAccessibleContext().setAccessibleName("jugar");

        jButtonTienda.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTienda.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/tienda_normal.png"))); // NOI18N
        jButtonTienda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/tienda_clicado.png"))); // NOI18N
        jButtonTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiendaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTienda);
        jButtonTienda.getAccessibleContext().setAccessibleName("tienda");

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_normal.png"))); // NOI18N
        jButtonSalir.setPreferredSize(new java.awt.Dimension(250, 23));
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_clicado.png"))); // NOI18N
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);
        jButtonSalir.getAccessibleContext().setAccessibleName("salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        OpcionesFijasLogica.deslogearse();
        this.setVisible(false);


    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        PantallaUsuarioDatos pad = new PantallaUsuarioDatos(parent, true, true);
        popup.hide();
        pad.setVisible(true);
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonMisPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisPreguntasActionPerformed
        // TODO add your handling code here:
        PantallaUsuarioPreguntas pup = new PantallaUsuarioPreguntas(parent, true);
        popup.hide();
        pup.setVisible(true);
    }//GEN-LAST:event_jButtonMisPreguntasActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
        PantallaSeleccionJuego psj = new PantallaSeleccionJuego(parent, true);
        popup.hide();
        psj.setVisible(true);
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiendaActionPerformed
        // TODO add your handling code here:

        PantallaComprarComodines pcc = new PantallaComprarComodines(parent, true);
        popup.hide();
        pcc.setVisible(true);
    }//GEN-LAST:event_jButtonTiendaActionPerformed

    private void ratonEntra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonEntra
        JButton jb = (JButton) evt.getSource();
        popup = VentanasLogica.mensajePopup(popup, jb.getAccessibleContext().getAccessibleName(), evt);
        popup.show();
    }//GEN-LAST:event_ratonEntra

    private void ratonSale(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonSale
        popup.hide();
    }//GEN-LAST:event_ratonSale


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonMisPreguntas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTienda;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
