/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quemquersermillonario.gui.usuario;

import com.sun.java.swing.plaf.windows.WindowsBorders;
import java.sql.Date;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import org.apache.commons.codec.digest.DigestUtils;
import quemquersermillonario.dao.interfaces.GenericDAO;
import quemquersermillonario.dao.interfaces.UsuarioDAO;
import quemquersermillonario.dao.interfaces.implementation.UsuarioDAOImpl;
import quemquersermillonario.dao.logica.ComprobacionText;
import quemquersermillonario.dao.logica.Lenguaje;
import quemquersermillonario.dao.logica.OpcionesFijasLogica;
import quemquersermillonario.dao.logica.VentanasLogica;
import quemquersermillonario.dto.Estudios;
import quemquersermillonario.dto.Usuario;
import quemquersermillonario.dto.complejas.OpcionesFijas;
import quemquersermillonario.gui.comboboxmodel.ComboBoxModelEstudios;

/**
 *
 * @author alvaro
 */
public class PantallaUsuarioDatos extends javax.swing.JDialog {

    /**
     * Creates new form PantallaUsuarioDatos
     */
    private Usuario usuario;
    private Boolean esModificacion = false;
    private UsuarioDAO usuarioDAO;
    private Popup popup;

    public PantallaUsuarioDatos(java.awt.Frame parent, boolean modal, boolean actualizar) {
        super(parent, modal);
        initComponents();
        usuarioDAO = new UsuarioDAOImpl();
        this.esModificacion = actualizar;
        this.jComboBoxEstudios.setModel(ComboBoxModelEstudios.getEstudiosComboBoxModel());

        if (!esModificacion) {
            this.setTitle(Lenguaje.getString("RegistroUsuario"));
            usuario = new Usuario();
        } else {
            this.setTitle(Lenguaje.getString("ActualizarUsuario"));
            usuario = OpcionesFijas.usuario;
            this.jTextFieldEmail.setEnabled(false);
            pasarObjetoACampos();
        }

        this.jLabelAnio.setText(Lenguaje.getString("Anio"));
        this.jLabelApellidos.setText(Lenguaje.getString("Apellidos"));
        this.jLabelEmail.setText(Lenguaje.getString("Email"));
        this.jLabelEstudios.setText(Lenguaje.getString("Estudios"));
        this.jLabelNombre.setText(Lenguaje.getString("Nombre"));
        this.jLabelPassword.setText(Lenguaje.getString("Password"));
        this.jLabelPasswordRepite.setText(Lenguaje.getString("RepitaPassword"));
        VentanasLogica.estilizarVentaja(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelPasswordRepite = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabelAnio = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jLabelEstudios = new javax.swing.JLabel();
        jComboBoxEstudios = new javax.swing.JComboBox<>();
        jLabelInformcionNombre = new javax.swing.JLabel();
        jLabelInformcionApellido1 = new javax.swing.JLabel();
        jLabelInformcionEmail2 = new javax.swing.JLabel();
        jLabelInformcionPassword3 = new javax.swing.JLabel();
        jLabelInformcionAnio4 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 8, 10, 20));

        jLabelNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldNombre.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldNombre);

        jLabelApellidos.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelApellidos.setText("Apellidos:");
        jPanel1.add(jLabelApellidos);

        jTextFieldApellidos.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldApellidos.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldApellidos);

        jLabelEmail.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        jPanel1.add(jLabelEmail);

        jTextFieldEmail.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldEmail.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jTextFieldEmail);

        jLabelPassword.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelPassword.setText("Password:");
        jPanel1.add(jLabelPassword);

        jPasswordField1.setSelectionColor(new java.awt.Color(255, 255, 0));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jPasswordField1);

        jLabelPasswordRepite.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelPasswordRepite.setText("Password:");
        jPanel1.add(jLabelPasswordRepite);

        jPasswordField2.setSelectionColor(new java.awt.Color(255, 255, 0));
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tamanoMaximo(evt);
            }
        });
        jPanel1.add(jPasswordField2);

        jLabelAnio.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelAnio.setText("Año Nacimiento:");
        jPanel1.add(jLabelAnio);

        jTextFieldAno.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jTextFieldAno.setSelectionColor(new java.awt.Color(255, 255, 0));
        jTextFieldAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAnoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldAno);

        jLabelEstudios.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabelEstudios.setText("Estudios:");
        jPanel1.add(jLabelEstudios);

        jComboBoxEstudios.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jComboBoxEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstudiosActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEstudios);

        jLabelInformcionNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/informacion.png"))); // NOI18N
        jLabelInformcionNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });

        jLabelInformcionApellido1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/informacion.png"))); // NOI18N
        jLabelInformcionApellido1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });

        jLabelInformcionEmail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/informacion.png"))); // NOI18N
        jLabelInformcionEmail2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });

        jLabelInformcionPassword3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/informacion.png"))); // NOI18N
        jLabelInformcionPassword3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });

        jLabelInformcionAnio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/informacion.png"))); // NOI18N
        jLabelInformcionAnio4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratonEntra(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratonSale(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 51, 204));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_normal.png"))); // NOI18N
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/salir_clicado.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonAceptar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(0, 51, 204));
        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/aceptar_normal.png"))); // NOI18N
        jButtonAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagenes/aceptar_clicado.png"))); // NOI18N
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInformcionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformcionApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformcionEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformcionPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformcionAnio4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInformcionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelInformcionApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabelInformcionEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabelInformcionPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabelInformcionAnio4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabelInformcionNombre.getAccessibleContext().setAccessibleName("Required.Nombre");
        jLabelInformcionApellido1.getAccessibleContext().setAccessibleName("Required.Apellido");
        jLabelInformcionEmail2.getAccessibleContext().setAccessibleName("Required.Email");
        jLabelInformcionEmail2.getAccessibleContext().setAccessibleDescription("");
        jLabelInformcionPassword3.getAccessibleContext().setAccessibleName("Required.Password");
        jLabelInformcionAnio4.getAccessibleContext().setAccessibleName("Required.Anio.Nacimiento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstudiosActionPerformed
        // TODO add your handling code here:
        //Cuando se cambia los estudios, se cambia en el usuario
    }//GEN-LAST:event_jComboBoxEstudiosActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:

        //Registro de Nuevo usuario
        if (!esModificacion) {

            if (ComprobacionText.jTextFieldObligatorio(jTextFieldNombre) && ComprobacionText.jTextFieldObligatorio(jTextFieldApellidos)
                    && ComprobacionText.jTextFieldObligatorio(jTextFieldEmail) && ComprobacionText.jAno(jTextFieldAno)
                    && ComprobacionText.jTextFieldEmail(jTextFieldEmail) && ComprobacionText.jPassword(jPasswordField1, jPasswordField2)) {
                pasarCamposAObjeto();
                usuario.setFechaCreacion(OpcionesFijas.fechaActual());
                if (usuarioDAO.buscarUsuarioEmail(usuario) == null) {
                    try {
                        usuarioDAO.guardar(usuario);
                        JOptionPane.showMessageDialog(this, "Enhorabuena ya se ha registrado", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                        this.setVisible(false);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                                "Se ha producido un error al registrarse, "
                                + "por favor contacte con el servicio técnico"
                                + "indicando el siguente mensaje\n"
                                + "Clase: " + this.getClass().getName() + "\n"
                                + "Error: " + e.getMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El Email que ha introducido ya esta en uso, por favor intro"
                            + "duzca otro, gracias.", "Error al registrarse", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Los datos introducidos no son validos, por favor reviselos", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        } //Actualizacion
        else {
            if (ComprobacionText.jTextFieldObligatorio(jTextFieldNombre) && ComprobacionText.jTextFieldObligatorio(jTextFieldApellidos)
                    && ComprobacionText.jTextFieldObligatorio(jTextFieldEmail) && ComprobacionText.jAno(jTextFieldAno)
                    && (((jPasswordField1.getText().length() > 0 && jPasswordField2.getText().length() > 0) && ComprobacionText.jPassword(jPasswordField1, jPasswordField2))
                    || (jPasswordField1.getText().length() == 0 && jPasswordField2.getText().length() == 0))) {
                try {
                    System.out.println("ID " + usuario.getIdUsuario());
                    pasarCamposAObjeto();
                    usuarioDAO.actualizar(usuario);
                    JOptionPane.showMessageDialog(this, "Los datos se han actualizado correctamente", "Actualizado", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Se ha producido un error al actualizar, "
                            + "por favor contacte con el servicio técnico"
                            + "indicando el siguente mensaje\n"
                            + "Clase: " + this.getClass().getName() + "\n"
                            + "Error: " + e.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Los datos introducidos no son validos, por favor reviselos", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }


    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldAnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnoKeyReleased
        // TODO add your handling code here:
        try {
            Integer.parseInt(jTextFieldAno.getText());
        } catch (Exception e) {
            jTextFieldAno.setText("");
        }
    }//GEN-LAST:event_jTextFieldAnoKeyReleased

    private void ratonEntra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonEntra
        // TODO add your handling code here:
        JLabel jl = (JLabel) evt.getSource();
        popup = VentanasLogica.mensajePopup(popup, jl.getAccessibleContext().getAccessibleName(), evt);
        popup.show();
    }//GEN-LAST:event_ratonEntra

    private void ratonSale(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratonSale
        // TODO add your handling code here:
        popup.hide();
    }//GEN-LAST:event_ratonSale

    private void tamanoMaximo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamanoMaximo
        // TODO add your handling code here:
        if (evt.getComponent() instanceof JPasswordField) {
            JPasswordField jtf = (JPasswordField) evt.getComponent();
            if (!ComprobacionText.comprobacionTamanoJPassword(jtf, 40)) {
                JOptionPane.showMessageDialog(this, Lenguaje.getString("Error.Texto.Longitud"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);
            }
        } else if (evt.getComponent() instanceof JTextField) {
            JTextField jtf = (JTextField) evt.getComponent();
            if (!ComprobacionText.comprobacionTamanoJTextField(jtf, 40)) {
                JOptionPane.showMessageDialog(this, Lenguaje.getString("Error.Texto.Longitud"), Lenguaje.getString("Error"), JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_tamanoMaximo

    private void pasarCamposAObjeto() {
        usuario.setNombre(jTextFieldNombre.getText());
        usuario.setApellidos(jTextFieldApellidos.getText());
        usuario.setEmail(jTextFieldEmail.getText());
        usuario.setAnoNacimiento(Integer.parseInt(jTextFieldAno.getText()));
        usuario.setActivo(1);
        if (!esModificacion || (esModificacion && jPasswordField1.getText().length() > 0)) {
            usuario.setPassword(DigestUtils.md5Hex(jPasswordField1.getText()));
        }
        usuario.setFechaModificacion(OpcionesFijas.fechaActual());
        usuario.setEstudios((Estudios) jComboBoxEstudios.getSelectedItem());

    }

    private void pasarObjetoACampos() {
        this.jTextFieldNombre.setText(usuario.getNombre());
        this.jTextFieldApellidos.setText(usuario.getApellidos());
        this.jTextFieldEmail.setText(usuario.getEmail());
        this.jTextFieldAno.setText(Integer.toString(usuario.getAnoNacimiento()));
        this.jComboBoxEstudios.setSelectedIndex(ComboBoxModelEstudios.getIndexOfEstudios(usuario.getEstudios()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxEstudios;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstudios;
    private javax.swing.JLabel jLabelInformcionAnio4;
    private javax.swing.JLabel jLabelInformcionApellido1;
    private javax.swing.JLabel jLabelInformcionEmail2;
    private javax.swing.JLabel jLabelInformcionNombre;
    private javax.swing.JLabel jLabelInformcionPassword3;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPasswordRepite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
